name: MysticLava
version: '${version}'
author: "Lecer"
website: lecer.ir
softdepend: [PlaceholderAPI, WorldEdit]
main: dev.lecer.mystic.mysticlava.core.MysticLava
description: An advanced floor is lava plugin
api-version: '1.13'
libraries:
  - mysql:mysql-connector-java:8.0.33
  - com.zaxxer:HikariCP:5.1.0